# GCRO data
Trying to get min max dates in QOL data.

In [5]:
import numpy as np
# Imports
import pandas as pd

In [6]:
# Data file paths
GCRO_2021 = '../../data/surveys/gcro-2021.dta'
GCRO_2018 = '../../data/surveys/gcro-2018.dta'
GCRO_2016 = '../../data/surveys/gcro-2016.dta'
df_gcro_2021 = pd.read_stata(GCRO_2021, convert_categoricals=False)
df_gcro_2018 = pd.read_stata(GCRO_2018, convert_categoricals=False)
df_gcro_2016 = pd.read_stata(GCRO_2016, convert_categoricals=False)

In [7]:
df_gcro_2016.head()

,SbjNum,S2,S2_2,S3_1,S3_2,Date,Duration,WardNumber,Municipality,S7,...,Q12_13,Q12_14,Q12_15,Q12_16,Q12_17,Q12_18,HH_Weight,Design_wgt,Bench_wgt,Bench_wgt_30002
0,21757821,2,2,1,2,2015-07-17,74,79800033,1,1,...,1,1,1,0,1,1,118.200000,335.366667,295.114845,1.000562
1,21839101,1,1,1,1,2015-07-20,79,79800043,1,1,...,0,0,0,1,1,1,115.327869,309.147541,252.507961,0.856107
2,21841544,2,1,1,3,2015-07-20,1442,79700057,3,1,...,1,0,0,0,0,0,184.100000,399.783333,467.334037,1.584457
3,21841617,1,2,2,1,2015-07-20,81,79700057,3,1,...,0,0,0,0,0,0,184.100000,399.783333,467.334037,1.584457
4,21848907,3,1,0,1,2015-07-20,61,79700058,3,1,...,1,0,0,0,0,1,132.907216,304.927835,290.372075,0.984482

In [8]:
# 2016
print('Min: ', np.min(df_gcro_2016['Date']))
print('Max: ', np.max(df_gcro_2016['Date']))
mean2016 = np.array(df_gcro_2016['Date'], dtype='datetime64[s]').view('i8').mean().astype('datetime64[s]')
print('Mean: ',mean2016)

totalInterviews2016 = len(df_gcro_2016)
print('Interview Count: ', totalInterviews2016)

Min:  2015-07-17 00:00:00
Max:  2016-05-17 00:00:00
Mean:  2015-10-19T03:02:49
Interview Count:  30002

In [9]:
df_gcro_2018.head()

,resp_id,ward,munic,munic_recode,region,ea_code,sp_code,sp_name,mp_code,mp_name,...,RESDU_WGT,DOWNSCALE_ResDU_wgt,F1servic,F2soclas,F3govsat,F4lifsat,F5health,F6safety,F7partic,QoLIndex_Data_Driven
0,7391,74201002,Emfuleni,4,Sedibeng,76010738,760004018,Sebokeng Hostels,760004,Sebokeng,...,142.405405,0.875060,8.603019,6.561684,3.472711,2.500000,5.981129,2.480409,10.000000,58.634769
1,7392,74201017,Emfuleni,4,Sedibeng,76010859,760004018,Sebokeng Hostels,760004,Sebokeng,...,136.574468,0.839230,6.916862,1.769811,1.622653,2.921062,5.341294,0.000000,10.000000,40.361269
2,7417,74201017,Emfuleni,4,Sedibeng,76010859,760004018,Sebokeng Hostels,760004,Sebokeng,...,136.574468,0.839230,6.916862,2.154136,0.000000,6.249121,7.307976,5.097104,4.585840,45.534463
3,7418,74201017,Emfuleni,4,Sedibeng,76010859,760004018,Sebokeng Hostels,760004,Sebokeng,...,136.574468,0.839230,8.313842,0.768650,2.614437,4.045359,10.000000,6.303237,10.000000,57.659429
4,7421,79800037,City of Johannesburg,2,City of Johannesburg,79810806,798030045,Klipspruit,798030,Soweto,...,140.443038,0.863002,6.844567,1.152975,1.157570,7.597574,7.352204,4.715503,7.875983,49.460237

In [10]:
# 2018
print('Min: ', np.min(df_gcro_2018['date']))
print('Max: ', np.max(df_gcro_2018['date']))
mean2018 = np.array(df_gcro_2018['date'], dtype='datetime64[s]').view('i8').mean().astype('datetime64[s]')
print('Mean: ',mean2018)

totalInterviews2018 = len(df_gcro_2018)
print('Interview Count: ', totalInterviews2018)

Min:  2017-10-31 00:00:00
Max:  2018-09-07 00:00:00
Mean:  2018-04-10T11:52:44
Interview Count:  24889

In [11]:
df_gcro_2021.head()

,unique_id,interview_date,Date_month,District_municipality,municipality_coded,Planning_region,Planning_region_code,ward_code,ea_code,adult_count,...,F1servic,F2soclas,F3govsat,F4lifsat,F5health,F6safety,F7partic,QoLIndex_Data_Driven,HH_WEIGHT,DOWNSCALE_MUN_PP_BENCHWGT
0,0002c645-1eda-4740-a065-0f40a24c0eaa,2021-02-20,5,1,1,Ekurhuleni_A,EKU_A,79700036,79710758,4,...,10.000000,7.795356,6.465669,7.500000,7.350730,5.580920,10.000000,79.555756,516.784167,1.228062
1,0006144d-bc67-479e-8482-37bd84c42233,2021-01-15,4,5,7,Merafong City,GT484,74804018,76610311,3,...,10.000000,7.765167,4.024354,3.667370,10.000000,4.064736,6.709857,70.034147,71.698750,0.208980
2,00151a00-e290-4ed7-ad05-9159e200ba48,2020-11-20,2,2,2,Johannesburg_D,JHB_D,79800043,79813663,3,...,8.564746,2.962554,4.851819,3.181259,10.000000,3.795571,2.535863,55.429275,475.072713,1.529085
3,00166da5-86bd-4628-bb60-2c1d6a6e66bd,2020-11-10,2,5,8,Mogale City,GT481,74801012,76310192,1,...,10.000000,3.195065,3.559272,5.840366,10.000000,8.143101,2.535863,64.974098,104.777569,0.235093
4,001ae7eb-a39b-4268-9f63-0588fa71b6e9,2020-11-05,2,2,2,Johannesburg_D,JHB_D,79800037,79810807,1,...,0.000000,2.578229,2.244718,0.000000,6.025358,1.652470,2.535863,19.383139,798.882790,1.250373

In [12]:
# 2021
print('Min: ', np.min(df_gcro_2021['interview_date']))
print('Max: ', np.max(df_gcro_2021['interview_date']))
mean2021 = np.array(df_gcro_2021['interview_date'], dtype='datetime64[s]').view('i8').mean().astype('datetime64[s]')
print('Mean: ',mean2021)

totalInterviews2021 = len(df_gcro_2021)
print('Interview Count: ', totalInterviews2021)

Min:  2020-10-06 00:00:00
Max:  2021-05-27 00:00:00
Mean:  2021-01-12T16:56:00
Interview Count:  13616

# Understanding keys

In [15]:
cols_2016 = df_gcro_2016.columns.values.tolist()
cols_2016

['SbjNum',
 'S2',
 'S2_2',
 'S3_1',
 'S3_2',
 'Date',
 'Duration',
 'WardNumber',
 'Municipality',
 'S7',
 'S8',
 'Q1',
 'Q1_Other_verbatim',
 'Q1_Recode_Dwelling',
 'Q1_1',
 'Q1_2',
 'Q1_3',
 'Q1_3_Other_verbatim',
 'Q1_4',
 'Q1_4_Other_verbatim',
 'Q1_5',
 'Q1_6',
 'Q1_7',
 'Q1_7_Other_verbatim',
 'Q1_8',
 'Q1_8_Other_verbatim',
 'Q1_9_1',
 'Q1_9_2',
 'Q1_9_3',
 'Q1_9_4',
 'Q1_9_5',
 'Q1_9_6',
 'Q1_9_7',
 'Q1_9_8',
 'Q1_9_9',
 'Q1_9_10',
 'Q1_9_11',
 'Q1_10',
 'Q1_11',
 'Q1_12',
 'Q1_12_Other_verbatim',
 'Q1_13',
 'Q1_14',
 'Q1_15',
 'Q1_16',
 'Q1_17',
 'Q1_18',
 'Q1_19',
 'Q1_20',
 'Q1_21',
 'Q1_22',
 'Q1_23',
 'Q1_24',
 'Q1_25',
 'Q1_26',
 'Q1_27',
 'Q1_28',
 'Q1_29',
 'Q1_30',
 'Q1_31',
 'Q1_32',
 'Q1_33',
 'Q2_1',
 'Q2_1_Recode',
 'Q2_2',
 'Q2_3',
 'Q2_4',
 'Q2_4_Recode',
 'Q2_5',
 'Q3_1',
 'Q3_2',
 'Q3_2_Other_verbatim',
 'Q3_3',
 'Q3_3_Other_verbatim',
 'Q3_4',
 'Q3_4_Other_verbatim',
 'Q3_5',
 'Q3_6',
 'Q4_1',
 'Q4_2',
 'Q4_3',
 'Q4_4_1',
 'Q4_4_2',
 'Q4_4_3',
 'Q4_4_4',
 'Q4_4_5',
 'Q4_4_6',
 'Q4_4_7',
 'Q4_4_8',
 'Q4_4_9',
 'Q4_4_10',
 'Q4_4_11',
 'Q4_4_12',
 'Q4_4_13',
 'Q4_4_Other_verbatim',
 'Q4_5',
 'Q4_6',
 'Q4_7',
 'Q4_8',
 'Q4_9',
 'Q4_10',
 'Q4_11',
 'Q4_12',
 'Q4_13',
 'Q4_14',
 'Q4_15',
 'Q4_16',
 'Q4_17',
 'Q4_18',
 'Q5_1',
 'Q5_2_1',
 'Q5_2_2',
 'Q5_2_3',
 'Q5_2_4',
 'Q5_2_5',
 'Q5_2_6',
 'Q5_2_7',
 'Q5_2_8',
 'Q5_2_9',
 'Q5_2_10',
 'Q5_2_Other_verbatim',
 'Q5_3',
 'Q5_4',
 'Q5_5',
 'Q5_6',
 'Q5_7_1',
 'Q5_7_2',
 'Q5_7_3',
 'Q5_7_4',
 'Q5_7_5',
 'Q5_7_6',
 'Q5_7_7',
 'Q5_7_8',
 'Q5_7_9',
 'Q5_7_10',
 'Q5_8',
 'Q5_9',
 'Q5_10',
 'Q5_11',
 'Q5_12',
 'Q5_13',
 'Q6_1',
 'Q6_2',
 'Q6_3',
 'Q6_3_Other_verbatim',
 'Q6_4_1',
 'Q6_4_2',
 'Q6_4_3',
 'Q6_4_4',
 'Q6_4_5',
 'Q6_4_6',
 'Q6_4_7',
 'Q6_4_8',
 'Q6_5',
 'Q6_5_Other_verbatim',
 'Q6_6',
 'Q6_7',
 'Q6_8',
 'Q6_9_Verbatim',
 'Q6_10',
 'Q6_11',
 'Q6_12_Verbatim',
 'Q6_13',
 'Q6_14',
 'Q6_15',
 'Q6_16',
 'Q6_17',
 'Q6_18',
 'Q6_19',
 'Q6_19_Verbatim',
 'Q6_20',
 'Q6_21',
 'Q6_22',
 'Q6_23',
 'Q6_24',
 'Q6_25',
 'Q6_26',
 'Q6_27',
 'Q6_28',
 'Q6_28_Other_verbatim',
 'Q6_29',
 'Q6_30',
 'Q6_31',
 'Q6_32',
 'Q6_33',
 'Q6_34',
 'Q6_35',
 'Q6_36',
 'Q6_37',
 'Q6_38',
 'Q6_39',
 'Q6_40',
 'Q6_41',
 'Q6_42',
 'Q6_43',
 'Q6_44',
 'Q6_45',
 'Q6_46',
 'Q6_47',
 'Q6_48',
 'Q6_49',
 'Q6_50',
 'Q6_51',
 'Q6_52',
 'Q6_53',
 'Q6_54',
 'Q6_55',
 'Q6_56',
 'Q6_57',
 'Q6_58',
 'Q6_59',
 'Q6_59_Other_verbatim',
 'Q7_1',
 'Q7_2',
 'Q7_3',
 'Q7_4',
 'Q7_5',
 'Q7_6',
 'Q7_7',
 'Q7_8',
 'Q7_9',
 'Q7_10',
 'Q7_11',
 'Q7_12',
 'Q8_1',
 'Q8_2',
 'Q8_2_Recode',
 'Q8_3',
 'Q8_4_Verbatim',
 'Q8_4_section',
 'Q8_4_division',
 'Q8_4_group',
 'Q8_4_class',
 'Q8_5',
 'Q8_6',
 'Q8_6_Other_verbatim',
 'Q8_7',
 'Q8_8_New',
 'Q8_9',
 'Q8_9_Other_verbatim',
 'Q8_10',
 'Q8_11',
 'Q8_12',
 'Q8_13',
 'Q8_14',
 'Q8_15',
 'Q8_16',
 'Q8_17',
 'Employment_Status',
 'Q8_18',
 'Q8_19',
 'Q8_20',
 'Q8_21',
 'Q8_22',
 'Q8_23',
 'Q8_24',
 'Q8_24_Other_verbatim',
 'Q8_25',
 'Q8_26',
 'Q8_26_Other_verbatim',
 'Q8_27_Verbatim',
 'Q8_28_1',
 'Q8_28_2',
 'Q8_28_3',
 'Q8_28_4',
 'Q8_28_5',
 'Q8_28_6',
 'Q8_28_7',
 'Q8_28_8',
 'Q8_28_9',
 'Q8_28_10',
 'Q8_28_11',
 'Q8_28_12',
 'Q8_28_13',
 'Q8_28_14',
 'Q8_28_15',
 'Q8_28_16',
 'Q8_28_17',
 'Q8_29',
 'Q8_30',
 'Q8_31_1',
 'Q8_31_2',
 'Q8_31_3',
 'Q8_31_4',
 'Q8_31_5',
 'Q8_31_6',
 'Q9_1',
 'Q9_2',
 'Q9_3',
 'Q9_4',
 'Q9_5',
 'Q9_6',
 'Q10_1',
 'Q10_2',
 'Q10_3_1',
 'Q10_3_2',
 'Q10_3_3',
 'Q10_3_4',
 'Q10_3_5',
 'Q10_3_6',
 'Q10_3_7',
 'Q10_3_8',
 'Q10_3_9',
 'Q10_3_10',
 'Q10_3_11',
 'Q10_3_Other_verbatim',
 'Q10_4',
 'Q11_1',
 'Q11_2',
 'Q11_3',
 'Q11_3_Other_verbatim',
 'Q11_4',
 'Q11_4_Other_verbatim',
 'Q11_5',
 'Q11_6',
 'Q11_6_Other_verbatim',
 'Q11_7_1',
 'Q11_7_2',
 'Q11_7_3',
 'Q11_8',
 'Q11_8_Other_verbatim',
 'Q11_9',
 'Q11_10',
 'Q11_10_Other_verbatim',
 'Q11_11',
 'Q11_12',
 'Q11_13',
 'Q11_13_Other_verbatim',
 'Q11_14_1',
 'Q11_14_2',
 'Q11_14_3',
 'Q11_14_4',
 'Q11_14_5',
 'Q11_14_6',
 'Q11_14_7',
 'Q11_14_8',
 'Q11_14_9',
 'Q11_14_10',
 'Q11_14_11',
 'Q11_14_12',
 'Q11_15',
 'Q11_16',
 'Q11_17',
 'Q11_18',
 'Q11_19',
 'Q11_20',
 'Q11_21',
 'Q11_22',
 'Q12_1',
 'Q12_1_Recode',
 'Q12_2',
 'Q12_3',
 'Q12_3_Recode',
 'Q12_4',
 'Q12_5',
 'Q12_5_Recode',
 'Q12_6',
 'Q12_7',
 'Q12_7_Recode',
 'Q12_8',
 'Q12_9',
 'Q12_10',
 'Q12_11',
 'Q12_12',
 'Q12_13',
 'Q12_14',
 'Q12_15',
 'Q12_16',
 'Q12_17',
 'Q12_18',
 'HH_Weight',
 'Design_wgt',
 'Bench_wgt',
 'Bench_wgt_30002']

In [16]:
cols_2018 = df_gcro_2018.columns.values.tolist()
cols_2018

['resp_id',
 'ward',
 'munic',
 'munic_recode',
 'region',
 'ea_code',
 'sp_code',
 'sp_name',
 'mp_code',
 'mp_name',
 'duration',
 'date',
 'dwelling_count',
 'adults_listed',
 'males_listed',
 'females_listed',
 'weight',
 'A1_Pop_group',
 'A2_Sex',
 'A3_dwelling',
 'A3_dwelling_recode',
 'A3_recode_2',
 'Q1_01_02_people',
 'Q1_01_02_people_recode',
 'Q1_02_rooms',
 'Q1_03_households',
 'Q1_04_tenure',
 'Q1_05_Ownership',
 'Q1_06_renting',
 'Q1_07_water',
 'Q1_08_water200m',
 'Q1_09_greywater',
 'Q1_10_waterflow',
 'Q1_11_toilet',
 'Q1_12_leaks',
 'Q1_13_behaviour',
 'Q1_14_borehole',
 'Q1_15_rainwater',
 'Q1_16_water_truck',
 'Q1_17_Interuptions',
 'Q1_18_water_cost',
 'Q1_19_water_clean',
 'Q1_20_toilet',
 'Q1_21_removal',
 'Q1_22_rubbish',
 'Q1_23_recycle',
 'Q1_24_recycle_bags',
 'Q1_25_1',
 'Q1_25_2',
 'Q1_25_3',
 'Q1_25_4',
 'Q1_25_5',
 'Q1_25_6',
 'Q1_25_7',
 'Q1_25_8',
 'Q1_25_9',
 'Q1_25_recode',
 'Q1_26_electricity_supplier',
 'Q1_27_lighting',
 'Q1_28_electricity_expenditure',
 'Q1_29_Interruptions',
 'Q1_30_geyser',
 'Q1_31_arrears',
 'Q1_32_water',
 'Q1_33_electricity',
 'Q1_34_evicted',
 'Q2_01_dwelling',
 'Q2_02_dwelling_dissatisfaction',
 'Q2_03_water',
 'Q2_04_sanitation',
 'Q2_05_waste',
 'Q2_06_energy',
 'Q2_07_munic_cost',
 'Q2_08_billing',
 'Q2_09_roads',
 'Q2_10_roads_dissatisfaction',
 'Q2_11_street_lights',
 'Q2_12_schools',
 'Q2_13_Health',
 'Q2_14_Drainage',
 'Q2_15_Libraries',
 'Q2_16_EMS',
 'Q2_17_metro',
 'Q2_18_gov_initiatives',
 'Q2_19_Parks',
 'Q3_01_birth_place',
 'Q3_01_recode',
 'Q3_02_country',
 'Q3_03_previous_residence',
 'Q3_04_year',
 'Q3_04_year_moved',
 'Q3_05_main_home',
 'Q3_06_home',
 'Q3_07_home',
 'Q3_08_visits',
 'Q3_09_visitors',
 'Q3_10_Retirement',
 'Q3_11_retirement_intention',
 'Q3_12_1',
 'Q3_12_2',
 'Q3_12_3',
 'Q3_12_4',
 'Q3_12_5',
 'Q3_12_6',
 'Q3_12_7',
 'Q3_12_8',
 'Q3_13_Language',
 'Q4_01_change',
 'Q4_02_major_problem',
 'Q4_03_community',
 'Q4_04_lengthof_stay',
 'Q4_05_reason_coming',
 'Q4_06_Leadership_perception',
 'Q4_07_1',
 'Q4_07_2',
 'Q4_07_3',
 'Q4_07_4',
 'Q4_07_5',
 'Q4_07_6',
 'Q4_07_7',
 'Q4_07_8',
 'Q4_07_9',
 'Q4_07_10',
 'Q4_07_11',
 'Q4_07_12',
 'Q5_01_frequent_trip',
 'Q5_01_recode',
 'Q5_02_non_movement',
 'Q5_02_01_trip',
 'Q5_03_destination',
 'Q5_03_1',
 'Q5_03_2',
 'Q5_03_2_codes',
 'Q5_03_3',
 'Q5_03_3_codes',
 'Q5_03_4',
 'Q5_03_4_codes',
 'Q5_04_time',
 'Q5_05_time_destination',
 'Q5_06_1',
 'Q5_06_2',
 'Q5_06_3',
 'Q5_06_4',
 'Q5_06_5',
 'Q5_06_6',
 'Q5_06_7',
 'Q5_06_8',
 'Q5_06_9',
 'Q5_06_10',
 'Q5_06_11',
 'Q5_06_12',
 'Q5_06_13',
 'Q5_06_14',
 'Q5_06_15',
 'Q5_07_Transp_Longdistance',
 'Q5_08_alternative_transport',
 'Q5_09_longest_travel',
 'Q5_11_BRT',
 'Q5_12_satisfaction_BRT',
 'Q5_13_why_use_BRT',
 'Q5_14_whatwould_encourage_BRT_us',
 'Q5_15_transport_expenditure',
 'Q5_16_transport_improvement',
 'Q5_17_etoll_payment',
 'Q5_18_proximity_public_transport',
 'Q6_01_internet',
 'Q6_02_1',
 'Q6_02_2',
 'Q6_02_3',
 'Q6_02_4',
 'Q6_02_5',
 'Q6_02_6',
 'Q6_02_7',
 'Q6_02_8',
 'Q6_02_9',
 'Q6_02_10',
 'Q6_03_internet',
 'Q6_04_1',
 'Q6_04_2',
 'Q6_04_3',
 'Q6_04_4',
 'Q6_04_5',
 'Q6_04_6',
 'Q6_05_municipal_broadband',
 'Q7_01_debt',
 'Q7_02_debt_repay',
 'Q7_03_1',
 'Q7_03_2',
 'Q7_03_3',
 'Q7_03_4',
 'Q7_03_5',
 'Q7_03_6',
 'Q7_03_7',
 'Q7_03_8',
 'Q7_03_9',
 'Q7_04_meal',
 'Q7_05_child',
 'Q7_06_benefit_food_scheme',
 'Q7_07_grow_vegetables',
 'Q7_08_monthly_expenditure_food',
 'Q7_09_How_difficult_saving',
 'Q8_01_registered',
 'Q8_02_voted',
 'Q8_03_reason_not_voting',
 'Q8_04_Party_change',
 'Q8_05_1',
 'Q8_05_2',
 'Q8_05_3',
 'Q8_05_4',
 'Q8_05_5',
 'Q8_05_6',
 'Q8_06_idp',
 'Q8_07_satis_IDP',
 'Q8_08_Participate_CBP',
 'Q8_09_satis_CBP',
 'Q8_10_NG',
 'Q8_11_PG',
 'Q8_12_LG',
 'Q8_13_councillor',
 'Q8_14_Government_level_done_more',
 'Q8_15_visit_gov',
 'Q8_16_dept',
 'Q8_17_assisted_reasonable_time',
 'Q8_18_treated_respectfully',
 'Q8_19_needs_satisfied',
 'Q8_20_batho_pele',
 'Q8_21_bribe',
 'Q8_22_municipal_communication',
 'Q8_23_democracy',
 'Q8_24_munic_listens',
 'Q8_25_munic_does',
 'Q8_26_munic_cares',
 'Q8_27_same_future',
 'Q8_28_dm_inclusion',
 'Q8_29_munic_belief',
 'Q8_30_munic_info',
 'Q8_31_Grants',
 'Q8_32_Water_sanitation',
 'Q8_33_Housing',
 'Q9_01_politics',
 'Q9_02_infl_dev',
 'Q9_03_country',
 'Q9_04_election',
 'Q9_05_judiciary',
 'Q9_06_enviro',
 'Q9_07_foreigners',
 'Q9_08_corruption',
 'Q9_09_press',
 'Q9_10_BW_trust',
 'Q9_11_alienation',
 'Q9_12_foreigners',
 'Q9_13_Environ_harm',
 'Q9_14_GP_water_crisis',
 'Q9_15_Black_opport_more',
 'Q9_16_Violenc_LBG',
 'Q9_17_Identify_self_with',
 'Q9_18_Price_up',
 'Q9_19_Parks_avail',
 'Q9_20_Interracial_dating',
 'Q10_01_money',
 'Q10_02_time',
 'Q10_03_marriage',
 'Q10_04_family',
 'Q10_05_friends',
 'Q10_06_living',
 'Q10_07_job_finding_difficulty',
 'Q10_08_leisure',
 'Q10_09_neighbourhood',
 'Q10_10_life',
 'Q10_11_abuse',
 'Q10_12_religion',
 'Q11_01_business_ownership',
 'Q11_02_business',
 'Q11_03_age',
 'Q11_03_recode',
 'Q11_04_business_type',
 'Q11_05_sector',
 'Q11_06_people',
 'Q11_07_employees',
 'Q11_08_business_description',
 'Q11_09_SMMes_support',
 'Q11_10_support_SMMes',
 'Q11_11_participate_survey',
 'Q11_12_working',
 'Q11_13_new_job',
 'Q11_14_unemployment_status',
 'Q11_15_unemployed',
 'Q11_16_looked_for_work',
 'Q11_17_search_work',
 'Q11_18_availability_emp',
 'Q11_19_period_unemployed',
 'Q11_20_employment',
 'Q11_21_sector',
 'Q11_22_work',
 'Q11_23_hours_work',
 'Q11_24_last_job',
 'Q11_25_imporant_job_consider',
 'Q12_01_crime',
 'Q12_02_victim',
 'Q12_03_day',
 'Q12_04_night',
 'Q12_05_home',
 'Q12_06_security_reside',
 'Q13_01_1',
 'Q13_01_2',
 'Q13_01_3',
 'Q13_01_4',
 'Q13_01_5',
 'Q13_01_6',
 'Q13_01_7',
 'Q13_01_8',
 'Q13_01_9',
 'Q13_01_10',
 'Q13_01_recode',
 'Q13_02_particip_charity',
 'Q13_03_1',
 'Q13_03_2',
 'Q13_03_3',
 'Q13_03_4',
 'Q13_03_5',
 'Q13_03_6',
 'Q13_03_7',
 'Q13_03_8',
 'Q13_03_9',
 'Q13_03_10',
 'Q13_03_11',
 'Q13_03_12',
 'Q13_04_participate_protest',
 'Q13_05_protest',
 'Q13_06_Last_Protest',
 'Q13_07_1',
 'Q13_07_2',
 'Q13_07_3',
 'Q13_07_4',
 'Q13_07_5',
 'Q13_07_6',
 'Q13_07_7',
 'Q13_07_8',
 'Q13_07_9',
 'Q13_07_10',
 'Q14_01_healthcare_services',
 'Q14_02_nonuse_public_health',
 'Q14_03_health_services',
 'Q14_04_medaid',
 'Q14_05_access',
 'Q14_06_reason_health_behavior',
 'Q14_07_frequency_mobile_clinic',
 'Q14_08_visited_health_woker',
 'Q14_09_1',
 'Q14_09_2',
 'Q14_09_3',
 'Q14_09_4',
 'Q14_09_5',
 'Q14_09_6',
 'Q14_09_7',
 'Q14_09_8',
 'Q14_09_9',
 'Q14_09_10',
 'Q14_10_HIV_test',
 'Q14_11_health',
 'Q14_12_work',
 'Q14_13_social',
 'Q14_14_pleasure',
 'Q14_15_depressed',
 'Q14_16_mental_problems',
 'Q14_17_emotional_support',
 'Q15_01_education',
 'Q15_01_education_recode',
 'Q15_02_age',
 'Q15_02_age_recode',
 'Q15_03_registered_student',
 'Q15_04_disability',
 'Q15_05_head',
 'Q15_06_dependants',
 'Q15_07_dependants',
 'Q15_08_primary_carer',
 'Q15_09_under18',
 'Q15_09_recode',
 'Q15_10_Timeto_school',
 'Q15_11_Schooling_type',
 'Q15_12_grant',
 'Q15_13_indigency_register',
 'Q15_14_formal',
 'Q15_15_informal',
 'Q15_16_remittances',
 'Q15_17_support',
 'Q15_18_renting',
 'Q15_19_savings',
 'Q15_20_income',
 'Q15_21_party_choice',
 'Q17_01_Interview_language',
 'Q17_02_1',
 'Q17_02_2',
 'Q17_02_3',
 'Q17_02_4',
 'Q17_02_5',
 'Q17_02_6',
 'Q17_02_7',
 'Q17_02_8',
 'Q17_02_9',
 'Q17_02_10',
 'Q17_02_11',
 'Q17_02_12',
 'Q17_02_13',
 'Q17_02_14',
 'RESDU_WGT',
 'DOWNSCALE_ResDU_wgt',
 'F1servic',
 'F2soclas',
 'F3govsat',
 'F4lifsat',
 'F5health',
 'F6safety',
 'F7partic',
 'QoLIndex_Data_Driven']

In [18]:
cols_2021 = df_gcro_2021.columns.values.tolist()
cols_2021

['unique_id',
 'interview_date',
 'Date_month',
 'District_municipality',
 'municipality_coded',
 'Planning_region',
 'Planning_region_code',
 'ward_code',
 'ea_code',
 'adult_count',
 'dur_mins',
 'dur_mins_recode',
 'interview_lang',
 'a1_pop_group',
 'a2_sex',
 'a3_dwelling_type',
 'a3_dwelling_type_recode',
 'q1_1_address',
 'q1_2c_rooms',
 'q1_2d_households',
 'q1_3_tenure',
 'q1_3a_ownership',
 'q1_3b_renting',
 'q1_4_water',
 'q1_5_water_meter',
 'q1_6_borehole',
 'q1_7_rainwater',
 'q1_8_water_clean',
 'q1_9_water_interruptions',
 'q1_10_toilet_type',
 'q1_11_removal',
 'q1_12_1_prepaid',
 'q1_12_2_postpaid',
 'q1_12_3_solar',
 'q1_12_4_generator',
 'q1_12_5_neighbour',
 'q1_12_6_car',
 'q1_12_7_elsewhere',
 'q1_12_8_dont_know',
 'q1_12_9_none',
 'Any_electricity',
 'Metered_connection',
 'Generating_electricity',
 'q1_12a_elec_generation',
 'q1_12b_elec_gen_plans',
 'q1_13_elec_loadshedding',
 'q1_13a_elec_plans_orig',
 'q1_13a_elec_plans_other',
 'q1_13a_elec_plans',
 'Generate_own_electricity',
 'Planning_off_grid',
 'q1_14_elec_interruptions',
 'q1_15_cooking',
 'q1_16_lighting',
 'q1_17_arrears',
 'q1_18_arrears_reason',
 'q1_19_1_flood',
 'q1_19_2_tremor',
 'q1_19_3_fire',
 'q1_19_4_heat',
 'q1_19_5_wind',
 'q1_19_6_lightning',
 'q1_19_7_hail',
 'q1_19_8_tornado',
 'q1_19_9_sinkhole',
 'q1_20_damages',
 'q2_1_dwelling',
 'q2_2_water',
 'q2_3_sewarage',
 'q2_4_waste',
 'q2_5_energy',
 'q2_6_service_cost',
 'q2_7_billing_satis',
 'q2_8_roads',
 'q2_9_street_lights',
 'q2_10_schools',
 'q2_11_gov_initiatives',
 'q2_12_covid',
 'q3_1_birth_prov',
 'q3_1_birth_prov_recode',
 'q3_2_birth_country',
 'q3_3_prev_residence',
 'q3_4_year_gp',
 'q3_4_year_gp_recode',
 'q3_5_length_stay',
 'q3_6_previous_home',
 'q3_6a_municipality',
 'q3_7_prev_neighbourhood',
 'q3_8_prev_dwelling_type',
 'q3_9_reason_moved',
 'q3_10_home',
 'q3_11_remittances',
 'q4_1_change',
 'q4_2_biggest_problem',
 'q4_3_community_trust',
 'q4_4_status',
 'q5_1_frequent_trip',
 'q5_2_non_movement',
 'q5_3_trip',
 'q5_1_3_frequent_trip_cons',
 'q5_4_1_trip_destination',
 'q5_4_2_trip_destination',
 'q5_5_depart_time',
 'q5_5_depart_time_recode',
 'q5_6_time_destination',
 'q5_6_time_destination_recode',
 'q5_7_mode_transport',
 'q5_8_pub_transport_waiting',
 'q5_9_pub_transport_safety',
 'q5_10_transport_exp',
 'q5_11_pub_transport_prox',
 'q5_11_pub_transport_prox_recode',
 'q5_12_ehail',
 'q5_13_road_accident',
 'q5_14_walk_week',
 'q5_14_1_work',
 'q5_14_2_relig',
 'q5_14_3_school',
 'q5_14_4_clinic',
 'q5_14_5_creche',
 'q5_14_6_spaza',
 'q5_14_7_mall',
 'q5_14_8_restaurant',
 'q5_14_9_friends',
 'q5_14_10_bank',
 'q5_14_11_internet',
 'q5_14_12_bar',
 'q5_14_13_park',
 'q5_14_14_library',
 'q5_14_15_sport',
 'q5_14_16_nowhere',
 'q5_14_17_other',
 'q6_1_internet',
 'q6_2_debt',
 'q6_2a_missed',
 'q6_3_1_landline',
 'q6_3_2_cell',
 'q6_3_3_tv',
 'q6_3_4_computer',
 'q6_3_5_radio',
 'q6_3_6_dstv',
 'q6_3_7_internet',
 'q6_3_8_car',
 'q6_3_9_bicycle',
 'q6_3_10_fridge',
 'q6_4_skip_meal',
 'q6_5_feed_children',
 'q6_5a_feeding',
 'q6_6_food',
 'q6_6_1_beans',
 'q6_6_2_polony',
 'q6_6_3_iqfchick',
 'q6_6_4_eggs',
 'q6_6_5_tinfish',
 'q6_6_6_meat',
 'q6_6_7_offal',
 'q6_6_8_dairy',
 'q6_6_9_nuts',
 'q6_7_food_satis',
 'q6_8_food_exp',
 'q7_1_registered',
 'q7_2_voted',
 'q7_3_rx_novote',
 'q7_4_ng',
 'q7_5_pg',
 'q7_6_lg',
 'q7_7_councillor',
 'q7_8_level_gov',
 'q7_9_batho_pele',
 'q7_10_gov_weakness',
 'q7_11_gov_trust',
 'q7_12_munic_comm',
 'q7_13_bribe',
 'q7_14_recent_bribe',
 'q7_15_1_housing',
 'q7_15_2_basic',
 'q7_15_3_billing',
 'q7_15_4_school',
 'q7_15_5_health',
 'q7_15_6_emerg',
 'q7_15_7_homeaff',
 'q7_15_8_traffic',
 'q7_15_9_license',
 'q7_15_10_saps',
 'q7_15_11_courts',
 'q7_15_12_tender',
 'q7_15_14_work',
 'q7_15_13_other',
 'q8_1_environ_harm',
 'q8_2_violence_foreigners',
 'q8_3_influence',
 'q8_4_country',
 'q8_5_election',
 'q8_6_gov_work_well',
 'q8_7_decision_making',
 'q8_7a_spread',
 'q8_8_bw_trust',
 'q8_9_water_crisis',
 'q8_10_violence_lgbt',
 'q8_11_alienation',
 'q8_12_foreigners',
 'q8_13_poverty',
 'q8_14_life_opp',
 'q8_15_racial_discrim',
 'q8_15a_job_search',
 'q8_16_nepotism',
 'q8_17_speed_gov_service',
 'q8_18_small_offence',
 'q8_19_school_choice',
 'q8_20_free_univ',
 'q8_21_rich_poor',
 'q8_22_rural_areas',
 'q8_23_belong',
 'q8_24_gcr',
 'q8_25_gcr',
 'q9_1_money',
 'q9_2_time',
 'q9_3_family_time',
 'q9_4_marriage',
 'q9_5_friends',
 'q9_6_living',
 'q9_7_leisure',
 'q9_8_neighbourhood',
 'q9_9_life',
 'q10_1_business',
 'q10_2_working',
 'q10_3_new_job',
 'q10_4_unemployed',
 'q10_5_not_looking',
 'q10_6_self_emp',
 'q10_7_sector',
 'q10_8_hours',
 'q10_9_satis',
 'q10_10_occupation_orig',
 'q10_10_occupation_maj',
 'q10_10_occupation_submaj',
 'q11_1_crime',
 'q11_2_crime_victim',
 'q11_3_daytime_safety',
 'q11_4_night_safety',
 'q11_5_home_safety',
 'q11_6_gov_security',
 'q12_1_1_church',
 'q12_1_2_social',
 'q12_1_3_stokvel',
 'q12_1_4_community',
 'q12_1_5_political',
 'q12_1_6_other',
 'Social_participation',
 'q12_2_1_ward',
 'q12_2_2_street',
 'q12_2_3_cdf',
 'q12_2_4_idp',
 'q12_2_5_mayor',
 'q12_2_6_sgb',
 'q12_2_7_cpf',
 'Political_participation',
 'q12_3_protest',
 'q12_4_rx_protest',
 'q12_5_partic_protest',
 'q13_1_healthcare',
 'q13_2_nonuse_public',
 'q13_3_health_proxim',
 'q13_4_health_satis',
 'q13_5_medical_aid',
 'q13_6_health_status',
 'q13_7_health_work',
 'q13_8_health_soc',
 'q13_9_pleasure',
 'q13_10_depressed',
 'PHQ2_score',
 'PHQ2_score_high',
 'q13_11_1_cancer',
 'q13_11_2_diabetes',
 'q13_11_3_asthma',
 'q13_11_4_pneumonia',
 'q13_11_5_heart',
 'q13_11_6_hypertension',
 'q13_11_7_hiv',
 'q13_11_8_tb',
 'q13_11_9_covid',
 'q13_12_1_avoid',
 'q13_12_2_transport',
 'q13_12_3_groceries',
 'q13_12_4_school',
 'q13_12_5_sanitiser',
 'q13_13_1_job',
 'q13_13_2_reduced',
 'q13_13_3_refuse',
 'q13_13_4_business',
 'q13_13_5_care',
 'q13_13_6_healthcare',
 'q13_13_7_eviction',
 'q13_14_srd_app',
 'q13_15_srd_rec',
 'q13_16_food_parcel',
 'q14_1_education',
 'q14_1_education_recode',
 'q14_2_age_topcode',
 'q14_2_age_recode',
 'q14_3_1_sight',
 'q14_3_2_hearing',
 'q14_3_3_speech',
 'q14_3_4_physical',
 'q14_3_5_intellectual',
 'q14_3_6_none',
 'q14_4_rel_status',
 'q14_5_people',
 'q14_5_people_recode',
 'q14_6_under18',
 'q14_6_under18_recode',
 'q14_7_60plus',
 'q14_7_60plus_recode',
 'q14_8_head',
 'q14_9_language',
 'q14_10_social_grant',
 'q14_11_indigency',
 'sc_consent',
 'q15_3_income',
 'q15_3_income_recode',
 'F1servic',
 'F2soclas',
 'F3govsat',
 'F4lifsat',
 'F5health',
 'F6safety',
 'F7partic',
 'QoLIndex_Data_Driven',
 'HH_WEIGHT',
 'DOWNSCALE_MUN_PP_BENCHWGT']

In [ ]:
# TODO: Compare 3 lists = create map of column name and date export to csv

# Columns

## Date

In [19]:
df_gcro_2016["Date"].head()

0   2015-07-17
1   2015-07-20
2   2015-07-20
3   2015-07-20
4   2015-07-20
Name: Date, dtype: datetime64[ns]

In [20]:
df_gcro_2018["date"].head()

0   2017-11-02
1   2017-11-02
2   2017-10-31
3   2017-11-02
4   2017-11-07
Name: date, dtype: datetime64[ns]

In [21]:
df_gcro_2021["interview_date"].head()

0   2021-02-20
1   2021-01-15
2   2020-11-20
3   2020-11-10
4   2020-11-05
Name: interview_date, dtype: datetime64[ns]

## Ward

In [29]:
print(len(df_gcro_2016["WardNumber"].unique()))
df_gcro_2016["WardNumber"].head()

508

0    79800033
1    79800043
2    79700057
3    79700057
4    79700058
Name: WardNumber, dtype: int32

In [30]:
print(len(df_gcro_2018["ward"].unique()))
df_gcro_2018["ward"].head()

529

0    74201002
1    74201017
2    74201017
3    74201017
4    79800037
Name: ward, dtype: object

In [31]:
print(len(df_gcro_2021["ward_code"].unique()))
df_gcro_2021["ward_code"].head()

529

0    79700036
1    74804018
2    79800043
3    74801012
4    79800037
Name: ward_code, dtype: int32

## Indexes

In [32]:
keys = ["F1servic",
        "F2soclas",
        "F3govsat",
        "F4lifsat",
        "F5health",
        "F6safety",
        "F7partic",
        "QoLIndex_Data_Driven",]

In [33]:
df_gcro_2021[keys].head()

,F1servic,F2soclas,F3govsat,F4lifsat,F5health,F6safety,F7partic,QoLIndex_Data_Driven
0,10.000000,7.795356,6.465669,7.500000,7.350730,5.580920,10.000000,79.555756
1,10.000000,7.765167,4.024354,3.667370,10.000000,4.064736,6.709857,70.034147
2,8.564746,2.962554,4.851819,3.181259,10.000000,3.795571,2.535863,55.429275
3,10.000000,3.195065,3.559272,5.840366,10.000000,8.143101,2.535863,64.974098
4,0.000000,2.578229,2.244718,0.000000,6.025358,1.652470,2.535863,19.383139

In [34]:
df_gcro_2018[keys].head()

,F1servic,F2soclas,F3govsat,F4lifsat,F5health,F6safety,F7partic,QoLIndex_Data_Driven
0,8.603019,6.561684,3.472711,2.500000,5.981129,2.480409,10.000000,58.634769
1,6.916862,1.769811,1.622653,2.921062,5.341294,0.000000,10.000000,40.361269
2,6.916862,2.154136,0.000000,6.249121,7.307976,5.097104,4.585840,45.534463
3,8.313842,0.768650,2.614437,4.045359,10.000000,6.303237,10.000000,57.659429
4,6.844567,1.152975,1.157570,7.597574,7.352204,4.715503,7.875983,49.460237

In [37]:
df_gcro_2016[[
 'HH_Weight',
 'Design_wgt',
 'Bench_wgt',
 'Bench_wgt_30002']].head()

    HH_Weight  Design_wgt   Bench_wgt  Bench_wgt_30002
0  118.200000  335.366667  295.114845         1.000562
1  115.327869  309.147541  252.507961         0.856107
2  184.100000  399.783333  467.334037         1.584457
3  184.100000  399.783333  467.334037         1.584457
4  132.907216  304.927835  290.372075         0.984482